package com.codepanel.models.enums;

public enum ScoreEventType {
    SUBMISSION_ACCEPTED,
    REVIEW_APPROVED,
    PROBLEM_ACCEPTED,
    COMMENT_LIKED,
    COMMENT_DISLIKED,
    PROBLEM_POSTED,
    PROBLEM_ANSWER_ACCEPTED,
    PROBLEM_ANSWER_UNACCEPTED,
    ACHIEVEMENT_AWARDED
}
